/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Admin_OptionsPK;

import B_Layer.EventBO;
import B_Layer.EventTypeBO;
import Entities.Event;
import Entities.EventType;
import View.EventDataPK.EventData;
import java.awt.BorderLayout;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jox
 */
public class TableEvents extends javax.swing.JPanel {
    private JPanel pnlContent;
    private Event event = new Event();
    private EventData eventData;
    private EventBO eventBO = new EventBO();
    private EventTypeBO eventType = new EventTypeBO();
    /**
     * Creates new form TableEvents
     */
    public TableEvents(JPanel pnlContent) {
        initComponents();
        this.pnlContent = pnlContent;
        eventData = new EventData(pnlContent);
        getEvents();
    }
    
    public void getEvents(){
            this.tblEvent.setModel(eventBO.getEvents());
            TableColumnModel tblModelColumn = this.tblEvent.getColumnModel();
            tblModelColumn.removeColumn(tblModelColumn.getColumn(0));
    }
    
    private Object checkTableSelection(JTable table, int column){
        Object user = null;
        if(!table.getSelectionModel().isSelectionEmpty())
        {
            int row = table.getSelectedRow();
            user = table.getModel().getValueAt(row, column);
            //return user;
        }
        return user;
    }
    
    private int getEventTypeId(){
        int id = -1;
        try {
            ArrayList<EventType> list = eventType.getEventTypeList();
            // user type id from the selected cmb item
            id = list.get(this.cmbEventType.getSelectedIndex()).getIdEvenType();
        } catch (SQLException ex) {
            Logger.getLogger(TableUsers.class.getName()).log(Level.SEVERE, null, ex);
        }
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvent = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnDeleteEvent = new javax.swing.JButton();
        btnUpdateEvent = new javax.swing.JButton();
        lblNameEvent = new javax.swing.JLabel();
        txtNameEvent = new javax.swing.JTextField();
        lblEventType = new javax.swing.JLabel();
        cmbEventType = new javax.swing.JComboBox<>();
        btnInsertEvent = new javax.swing.JButton();
        btnEventData = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(94, 4, 32));
        jPanel1.setMaximumSize(new java.awt.Dimension(834, 578));
        jPanel1.setMinimumSize(new java.awt.Dimension(834, 578));

        tblEvent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEvent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEventMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEvent);

        jPanel2.setBackground(new java.awt.Color(152, 12, 51));

        btnDeleteEvent.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnDeleteEvent.setText("DELETE");
        btnDeleteEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEventActionPerformed(evt);
            }
        });

        btnUpdateEvent.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUpdateEvent.setText("UPDATE");
        btnUpdateEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateEventActionPerformed(evt);
            }
        });

        lblNameEvent.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblNameEvent.setForeground(new java.awt.Color(255, 255, 255));
        lblNameEvent.setText("Name");

        lblEventType.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblEventType.setForeground(new java.awt.Color(255, 255, 255));
        lblEventType.setText("Event Type");

        cmbEventType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbEventType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mundial", "mundial femenino" }));
        cmbEventType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEventTypeActionPerformed(evt);
            }
        });

        btnInsertEvent.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnInsertEvent.setText("INSERT");
        btnInsertEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertEventActionPerformed(evt);
            }
        });

        btnEventData.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnEventData.setText("Event Data");
        btnEventData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameEvent)
                            .addComponent(lblEventType))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNameEvent, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(cmbEventType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateEvent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnEventData)
                                .addGap(61, 61, 61)
                                .addComponent(btnDeleteEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnInsertEvent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnInsertEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnUpdateEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNameEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNameEvent, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteEvent, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEventType)
                    .addComponent(cmbEventType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEventData, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblEventMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEventMouseClicked
        int selection = this.tblEvent.rowAtPoint(evt.getPoint());
        String type = this.tblEvent.getValueAt(selection, 0)+"";
        
        this.txtNameEvent.setText(this.tblEvent.getValueAt(selection,1)+"");
    }//GEN-LAST:event_tblEventMouseClicked

    private void btnDeleteEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEventActionPerformed
        if(this.checkTableSelection(this.tblEvent, 0) != null){
            int idEvent = Integer.parseInt((String) checkTableSelection(this.tblEvent, 0));
            //  System.out.println(this.eventBO.deleteEvent(idEvent));
            this.getEvents();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteEventActionPerformed

    private void btnUpdateEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateEventActionPerformed
        if (this.checkTableSelection(this.tblEvent,0) != null){
            
            int idEvent = Integer.parseInt((String) checkTableSelection(this.tblEvent, 0));

            this.event.setIdEvent(idEvent);
            this.event.setIdEvenType(this.getEventTypeId());
            this.event.setName(this.txtNameEvent.getText());
            
            System.out.println(this.eventBO.updateEvent(event));
            this.getEvents();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateEventActionPerformed

    private void cmbEventTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEventTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEventTypeActionPerformed

    private void btnInsertEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertEventActionPerformed
        if (!(this.txtNameEvent.getText().isEmpty())){
            
            if (this.cmbEventType.getSelectedItem().toString().toLowerCase().equals("mundial"))
                this.event.setIdEvenType(3);
            else
                this.event.setIdEvenType(4);

            this.event.setName(this.txtNameEvent.getText());
            
            System.out.println(eventBO.insertEvent(event));
            this.getEvents();
        }
        else {
            JOptionPane.showMessageDialog(null, "Invalid name, null value encountered");
        }
    }//GEN-LAST:event_btnInsertEventActionPerformed

    private void btnEventDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventDataActionPerformed
        if (this.checkTableSelection(this.tblEvent,0) != null){
            // sets the event id
            int idEvent = Integer.parseInt((String) checkTableSelection(tblEvent, 0));
            this.eventData.setIdEventToSubEntities(idEvent);
            this.eventData.setSize(834, 567);
            this.eventData.setLocation(0,0);
            pnlContent.removeAll();
            pnlContent.add(this.eventData,BorderLayout.CENTER);
            pnlContent.revalidate();
            pnlContent.repaint();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnEventDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteEvent;
    private javax.swing.JButton btnEventData;
    private javax.swing.JButton btnInsertEvent;
    private javax.swing.JButton btnUpdateEvent;
    private javax.swing.JComboBox<String> cmbEventType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEventType;
    private javax.swing.JLabel lblNameEvent;
    private javax.swing.JTable tblEvent;
    private javax.swing.JTextField txtNameEvent;
    // End of variables declaration//GEN-END:variables
}
