/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.EventDataPK;

/**
 *
 * @author jox
 */
public class EventData extends javax.swing.JPanel {

    /**
     * Creates new form EventData
     */
    public EventData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPeople = new javax.swing.JButton();
        btnContinents = new javax.swing.JButton();
        btnStadiums = new javax.swing.JButton();
        btnHelpers = new javax.swing.JButton();
        btnTeams = new javax.swing.JButton();
        btnWorkers = new javax.swing.JButton();
        btnNews6 = new javax.swing.JButton();
        btnNews7 = new javax.swing.JButton();
        btnNews8 = new javax.swing.JButton();
        btnNews9 = new javax.swing.JButton();
        btnNews10 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(94, 4, 32));
        jPanel1.setMaximumSize(new java.awt.Dimension(834, 578));
        jPanel1.setMinimumSize(new java.awt.Dimension(834, 578));

        btnPeople.setBackground(new java.awt.Color(152, 12, 51));
        btnPeople.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnPeople.setForeground(new java.awt.Color(255, 255, 255));
        btnPeople.setText("People");
        btnPeople.setBorder(null);
        btnPeople.setMaximumSize(new java.awt.Dimension(220, 50));
        btnPeople.setMinimumSize(new java.awt.Dimension(220, 50));
        btnPeople.setPreferredSize(new java.awt.Dimension(220, 50));
        btnPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeopleActionPerformed(evt);
            }
        });

        btnContinents.setBackground(new java.awt.Color(152, 12, 51));
        btnContinents.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnContinents.setForeground(new java.awt.Color(255, 255, 255));
        btnContinents.setText("Continents");
        btnContinents.setBorder(null);
        btnContinents.setMaximumSize(new java.awt.Dimension(220, 50));
        btnContinents.setMinimumSize(new java.awt.Dimension(220, 50));
        btnContinents.setPreferredSize(new java.awt.Dimension(220, 50));
        btnContinents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinentsActionPerformed(evt);
            }
        });

        btnStadiums.setBackground(new java.awt.Color(152, 12, 51));
        btnStadiums.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnStadiums.setForeground(new java.awt.Color(255, 255, 255));
        btnStadiums.setText("Stadiums");
        btnStadiums.setBorder(null);
        btnStadiums.setMaximumSize(new java.awt.Dimension(220, 50));
        btnStadiums.setMinimumSize(new java.awt.Dimension(220, 50));
        btnStadiums.setPreferredSize(new java.awt.Dimension(220, 50));
        btnStadiums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStadiumsActionPerformed(evt);
            }
        });

        btnHelpers.setBackground(new java.awt.Color(152, 12, 51));
        btnHelpers.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnHelpers.setForeground(new java.awt.Color(255, 255, 255));
        btnHelpers.setText("Helpers");
        btnHelpers.setBorder(null);
        btnHelpers.setMaximumSize(new java.awt.Dimension(220, 50));
        btnHelpers.setMinimumSize(new java.awt.Dimension(220, 50));
        btnHelpers.setPreferredSize(new java.awt.Dimension(220, 50));
        btnHelpers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHelpersActionPerformed(evt);
            }
        });

        btnTeams.setBackground(new java.awt.Color(152, 12, 51));
        btnTeams.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnTeams.setForeground(new java.awt.Color(255, 255, 255));
        btnTeams.setText("Teams");
        btnTeams.setBorder(null);
        btnTeams.setMaximumSize(new java.awt.Dimension(220, 50));
        btnTeams.setMinimumSize(new java.awt.Dimension(220, 50));
        btnTeams.setPreferredSize(new java.awt.Dimension(220, 50));
        btnTeams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeamsActionPerformed(evt);
            }
        });

        btnWorkers.setBackground(new java.awt.Color(152, 12, 51));
        btnWorkers.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnWorkers.setForeground(new java.awt.Color(255, 255, 255));
        btnWorkers.setText("Workers");
        btnWorkers.setBorder(null);
        btnWorkers.setMaximumSize(new java.awt.Dimension(220, 50));
        btnWorkers.setMinimumSize(new java.awt.Dimension(220, 50));
        btnWorkers.setPreferredSize(new java.awt.Dimension(220, 50));
        btnWorkers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkersActionPerformed(evt);
            }
        });

        btnNews6.setBackground(new java.awt.Color(152, 12, 51));
        btnNews6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNews6.setForeground(new java.awt.Color(255, 255, 255));
        btnNews6.setText("Phases");
        btnNews6.setBorder(null);
        btnNews6.setMaximumSize(new java.awt.Dimension(220, 50));
        btnNews6.setMinimumSize(new java.awt.Dimension(220, 50));
        btnNews6.setPreferredSize(new java.awt.Dimension(220, 50));
        btnNews6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNews6ActionPerformed(evt);
            }
        });

        btnNews7.setBackground(new java.awt.Color(152, 12, 51));
        btnNews7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNews7.setForeground(new java.awt.Color(255, 255, 255));
        btnNews7.setText("Groups");
        btnNews7.setBorder(null);
        btnNews7.setMaximumSize(new java.awt.Dimension(220, 50));
        btnNews7.setMinimumSize(new java.awt.Dimension(220, 50));
        btnNews7.setPreferredSize(new java.awt.Dimension(220, 50));
        btnNews7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNews7ActionPerformed(evt);
            }
        });

        btnNews8.setBackground(new java.awt.Color(152, 12, 51));
        btnNews8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNews8.setForeground(new java.awt.Color(255, 255, 255));
        btnNews8.setText("Users");
        btnNews8.setBorder(null);
        btnNews8.setMaximumSize(new java.awt.Dimension(220, 50));
        btnNews8.setMinimumSize(new java.awt.Dimension(220, 50));
        btnNews8.setPreferredSize(new java.awt.Dimension(220, 50));
        btnNews8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNews8ActionPerformed(evt);
            }
        });

        btnNews9.setBackground(new java.awt.Color(152, 12, 51));
        btnNews9.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNews9.setForeground(new java.awt.Color(255, 255, 255));
        btnNews9.setText("Catalogs");
        btnNews9.setBorder(null);
        btnNews9.setMaximumSize(new java.awt.Dimension(220, 50));
        btnNews9.setMinimumSize(new java.awt.Dimension(220, 50));
        btnNews9.setPreferredSize(new java.awt.Dimension(220, 50));
        btnNews9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNews9ActionPerformed(evt);
            }
        });

        btnNews10.setBackground(new java.awt.Color(152, 12, 51));
        btnNews10.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnNews10.setForeground(new java.awt.Color(255, 255, 255));
        btnNews10.setText("News");
        btnNews10.setBorder(null);
        btnNews10.setMaximumSize(new java.awt.Dimension(220, 50));
        btnNews10.setMinimumSize(new java.awt.Dimension(220, 50));
        btnNews10.setPreferredSize(new java.awt.Dimension(220, 50));
        btnNews10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNews10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnContinents, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHelpers, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNews7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnStadiums, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btnPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnWorkers, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNews6, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNews8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTeams, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNews10, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115)
                .addComponent(btnNews9, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(158, 158, 158))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPeople, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStadiums, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnContinents, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHelpers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnWorkers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTeams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNews7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNews6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNews8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNews9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNews10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeopleActionPerformed

    }//GEN-LAST:event_btnPeopleActionPerformed

    private void btnContinentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinentsActionPerformed

    private void btnStadiumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStadiumsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStadiumsActionPerformed

    private void btnHelpersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHelpersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHelpersActionPerformed

    private void btnTeamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeamsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTeamsActionPerformed

    private void btnWorkersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnWorkersActionPerformed

    private void btnNews6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNews6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNews6ActionPerformed

    private void btnNews7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNews7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNews7ActionPerformed

    private void btnNews8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNews8ActionPerformed

    }//GEN-LAST:event_btnNews8ActionPerformed

    private void btnNews9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNews9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNews9ActionPerformed

    private void btnNews10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNews10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNews10ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinents;
    private javax.swing.JButton btnHelpers;
    private javax.swing.JButton btnNews10;
    private javax.swing.JButton btnNews6;
    private javax.swing.JButton btnNews7;
    private javax.swing.JButton btnNews8;
    private javax.swing.JButton btnNews9;
    private javax.swing.JButton btnPeople;
    private javax.swing.JButton btnStadiums;
    private javax.swing.JButton btnTeams;
    private javax.swing.JButton btnWorkers;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
