/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.EventDataPK;

import B_Layer.NewsBO;
import Entities.News;
import View.myTableCellRenderer;
import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jox
 */
public class TableNews extends javax.swing.JPanel {
    private final NewsBO newsBO = new NewsBO();
    private final News news = new News();
    private String photo = "";
    private int idEvent;
    
    /**
     * Creates new form TableConsults
     */
    public TableNews() {
        initComponents();
        //this.btnInsert.setVisible(false);
    }
    
    public void getNews(){
            tblNews.setModel(newsBO.getNews());
            TableColumnModel tblModelColumn = tblNews.getColumnModel();
            tblModelColumn.removeColumn(tblModelColumn.getColumn(0));
            showPhotos(this.tblNews, 6);
            fixWidth(this.tblNews);
    }
    
    public void showPhotos(JTable table, int columnPhotos){
        int rows = table.getRowCount();
        // Get Photo column and override TableCellRenderer class component method (getTableCellRendererComponent
        table.getColumn("photo").setCellRenderer(new myTableCellRenderer(200));
        for (int i = 0; i < rows; i++){
            String path = (String) this.tblNews.getValueAt(i, columnPhotos);
            ImageIcon imageIcon = new ImageIcon(path);
            JLabel lblPhoto = new JLabel();
            Image imageResized = imageIcon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            lblPhoto.setIcon(new ImageIcon(imageResized));
            this.tblNews.setValueAt(lblPhoto, i, columnPhotos);
            
        }
    }
    
    public void fixWidth(JTable table){
        int rows = table.getColumnCount();

        for (int i = 0; i < rows; i++){
            table.getColumnModel().getColumn(i).setPreferredWidth(200);
        }
    }
    
    private Object checkTableSelection(JTable table, int column){
        Object user = null;
        if(!table.getSelectionModel().isSelectionEmpty())
        {
            int row = table.getSelectedRow();
            user = table.getModel().getValueAt(row, column);
            //return user;
        }
        return user;
    }

    public int getIdEvent() {
        return idEvent;
    }

    public void setIdEvent(int idEvent) {
        this.idEvent = idEvent;
        this.newsBO.setIdEvent(idEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNews = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnDeleteNews = new javax.swing.JButton();
        btnUpdateNews = new javax.swing.JButton();
        lblTitleNews = new javax.swing.JLabel();
        txtTitleNews = new javax.swing.JTextField();
        btnInsertNews = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTextNews = new javax.swing.JTextArea();
        lblDateNews = new javax.swing.JLabel();
        lblTextNews = new javax.swing.JLabel();
        txtAuthorNews = new javax.swing.JTextField();
        lblAuthorNews = new javax.swing.JLabel();
        lblPhotoNews = new javax.swing.JLabel();
        lblLogoPhoto = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        dtDateNews = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(94, 4, 32));
        jPanel1.setMaximumSize(new java.awt.Dimension(834, 578));
        jPanel1.setMinimumSize(new java.awt.Dimension(834, 578));

        tblNews.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblNews.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblNews.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNewsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNews);

        jPanel2.setBackground(new java.awt.Color(152, 12, 51));

        btnDeleteNews.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnDeleteNews.setText("DELETE");
        btnDeleteNews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteNewsActionPerformed(evt);
            }
        });

        btnUpdateNews.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUpdateNews.setText("UPDATE");
        btnUpdateNews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNewsActionPerformed(evt);
            }
        });

        lblTitleNews.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTitleNews.setForeground(new java.awt.Color(255, 255, 255));
        lblTitleNews.setText("Title");

        btnInsertNews.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnInsertNews.setText("INSERT");
        btnInsertNews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertNewsActionPerformed(evt);
            }
        });

        txtTextNews.setColumns(20);
        txtTextNews.setRows(5);
        jScrollPane2.setViewportView(txtTextNews);

        lblDateNews.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblDateNews.setForeground(new java.awt.Color(255, 255, 255));
        lblDateNews.setText("Date");

        lblTextNews.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblTextNews.setForeground(new java.awt.Color(255, 255, 255));
        lblTextNews.setText("Text");

        lblAuthorNews.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblAuthorNews.setForeground(new java.awt.Color(255, 255, 255));
        lblAuthorNews.setText("Author");

        lblPhotoNews.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblPhotoNews.setForeground(new java.awt.Color(255, 255, 255));
        lblPhotoNews.setText("Photo");

        lblLogoPhoto.setBackground(new java.awt.Color(255, 255, 255));

        btnBrowse.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        dtDateNews.setDateFormatString("dd-MM-yy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleNews)
                    .addComponent(lblTextNews)
                    .addComponent(lblAuthorNews)
                    .addComponent(lblPhotoNews))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtTitleNews, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInsertNews, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtAuthorNews, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDateNews)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dtDateNews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateNews, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(lblLogoPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addComponent(btnDeleteNews, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTitleNews, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTitleNews))
                    .addComponent(btnInsertNews, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTextNews))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDateNews)
                            .addComponent(btnUpdateNews, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnDeleteNews, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                                .addComponent(lblLogoPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAuthorNews)
                                    .addComponent(txtAuthorNews, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPhotoNews)
                                    .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(dtDateNews, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(15, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblNewsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNewsMouseClicked

    }//GEN-LAST:event_tblNewsMouseClicked

    private void btnDeleteNewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteNewsActionPerformed
        if(this.checkTableSelection(this.tblNews, 0) != null){
            int idNews = Integer.parseInt((String) checkTableSelection(this.tblNews, 0));
            System.out.println(this.newsBO.deleteNews(idNews));
            this.getNews();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteNewsActionPerformed

    private void btnUpdateNewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNewsActionPerformed
        if (this.checkTableSelection(this.tblNews,0) != null){
            
            if (!((JTextField)this.dtDateNews.getDateEditor().getUiComponent()).getText().isEmpty()){
                java.util.Date utilDate = this.dtDateNews.getDate();
                java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
                this.news.setDate(sqlDate);
            }
            
            int idNews = Integer.parseInt((String) checkTableSelection(this.tblNews, 0));
            
            this.news.setIdNews(idNews);
            this.news.setIdEvent(this.idEvent);
            this.news.setTitle(this.txtTitleNews.getText());
            this.news.setText(this.txtTextNews.getText());
            this.news.setAuthor(this.txtAuthorNews.getText());
            this.news.setPhoto(this.photo);
           
            System.out.println(newsBO.updateNews(news));
            this.getNews();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateNewsActionPerformed

    private void btnInsertNewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertNewsActionPerformed
        if (!(this.txtTitleNews.getText().isEmpty() || this.txtTextNews.getText().isEmpty()
                || this.txtAuthorNews.getText().isEmpty() || this.photo.isEmpty()
                || ((JTextField)this.dtDateNews.getDateEditor().getUiComponent()).getText().isEmpty())){
            
            java.util.Date utilDate = this.dtDateNews.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            
            this.news.setIdEvent(this.idEvent);
            this.news.setTitle(this.txtTitleNews.getText());
            this.news.setText(this.txtTextNews.getText());
            this.news.setAuthor(this.txtAuthorNews.getText());
            this.news.setDate(sqlDate);
            this.news.setPhoto(this.photo);
           
            System.out.println(newsBO.insertNews(news));
            this.getNews();
        }
        else {
            JOptionPane.showMessageDialog(null, "Invalid event, title, text, author, date or photo,"
                    + " null value encountered");
        }
    }//GEN-LAST:event_btnInsertNewsActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        JFileChooser browseImageFile = new JFileChooser();
        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);

        if (showOpenDialogue == JFileChooser.APPROVE_OPTION){
            File selectedImageFile = browseImageFile.getSelectedFile();
            this.photo = selectedImageFile.getAbsolutePath();
            //Display image on jlabel
            ImageIcon image = new ImageIcon(this.photo);
            // Resize image to fit jlable
            Image imageResized = image.getImage().getScaledInstance(this.lblLogoPhoto.getWidth(),this.lblLogoPhoto.getHeight(), Image.SCALE_SMOOTH);

            this.lblLogoPhoto.setIcon(new ImageIcon(imageResized));
        }
    }//GEN-LAST:event_btnBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnDeleteNews;
    private javax.swing.JButton btnInsertNews;
    private javax.swing.JButton btnUpdateNews;
    private com.toedter.calendar.JDateChooser dtDateNews;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAuthorNews;
    private javax.swing.JLabel lblDateNews;
    private javax.swing.JLabel lblLogoPhoto;
    private javax.swing.JLabel lblPhotoNews;
    private javax.swing.JLabel lblTextNews;
    private javax.swing.JLabel lblTitleNews;
    private javax.swing.JTable tblNews;
    private javax.swing.JTextField txtAuthorNews;
    private javax.swing.JTextArea txtTextNews;
    private javax.swing.JTextField txtTitleNews;
    // End of variables declaration//GEN-END:variables
}
