/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.EventDataPK;

import B_Layer.DistrictBO;
import Entities.District;
import java.awt.BorderLayout;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jox
 */
public class TableDistricts extends javax.swing.JPanel {
    private JPanel pnlContent;
    private final DistrictBO districtBO = new DistrictBO();
    private final District district = new District();
    private TableAddresses address;
    /**
     * Creates new form TableDistricts
     */
    public TableDistricts(JPanel pnlContent) {
        this.pnlContent = pnlContent;
        this.address = new TableAddresses();
        initComponents();
        getDistricts();
    }
    
    public void SetCantonToDistrict(int id){
        district.setIdCanton(id);
    }
    public void getDistricts(){
            this.tblDistrict.setModel(districtBO.getDistricts());
            TableColumnModel tblModelColumn = this.tblDistrict.getColumnModel();
            tblModelColumn.removeColumn(tblModelColumn.getColumn(0));
    }
    
    private Object checkTableSelection(JTable table, int column){
        Object user = null;
        if(!table.getSelectionModel().isSelectionEmpty())
        {
            int row = table.getSelectedRow();
            user = table.getModel().getValueAt(row, column);
            //return user;
        }
        return user;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDistrict = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnManageAdresses = new javax.swing.JButton();
        btnUpdateDistrict = new javax.swing.JButton();
        lblNameDistrict = new javax.swing.JLabel();
        txtNameDistrict = new javax.swing.JTextField();
        btnInsertDistrict = new javax.swing.JButton();
        lblDistricts = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(94, 4, 32));
        jPanel1.setMaximumSize(new java.awt.Dimension(834, 578));
        jPanel1.setMinimumSize(new java.awt.Dimension(834, 578));

        tblDistrict.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblDistrict.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDistrictMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDistrict);

        jPanel2.setBackground(new java.awt.Color(152, 12, 51));

        btnManageAdresses.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnManageAdresses.setText("Manage Adresses");
        btnManageAdresses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdressesActionPerformed(evt);
            }
        });

        btnUpdateDistrict.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUpdateDistrict.setText("UPDATE");
        btnUpdateDistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDistrictActionPerformed(evt);
            }
        });

        lblNameDistrict.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblNameDistrict.setForeground(new java.awt.Color(255, 255, 255));
        lblNameDistrict.setText("Name");

        btnInsertDistrict.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnInsertDistrict.setText("INSERT");
        btnInsertDistrict.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertDistrictActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManageAdresses)
                    .addComponent(btnInsertDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNameDistrict)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(284, 284, 284)
                        .addComponent(btnUpdateDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnInsertDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNameDistrict, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNameDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdateDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addComponent(btnManageAdresses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        lblDistricts.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblDistricts.setForeground(new java.awt.Color(255, 255, 255));
        lblDistricts.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDistricts.setText("Districts");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDistricts, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblDistricts, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDistrictMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDistrictMouseClicked
        int selection = this.tblDistrict.rowAtPoint(evt.getPoint());
        String type = this.tblDistrict.getValueAt(selection, 0)+"";
        
        this.txtNameDistrict.setText(this.tblDistrict.getValueAt(selection, 1)+"");
    }//GEN-LAST:event_tblDistrictMouseClicked

    private void btnManageAdressesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdressesActionPerformed
        if(this.checkTableSelection(tblDistrict, WIDTH) != null ){
            int idDistrict = Integer.parseInt((String) checkTableSelection(tblDistrict, 0));
            this.address.SetDistrictToAddress(idDistrict);
            this.address.setSize(834, 567);
            this.address.setLocation(0,0);
            pnlContent.removeAll();
            pnlContent.add(this.address,BorderLayout.CENTER);
            pnlContent.revalidate();
            pnlContent.repaint();
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Canton");
        }
        
    }//GEN-LAST:event_btnManageAdressesActionPerformed

    private void btnUpdateDistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDistrictActionPerformed
        if (this.checkTableSelection(tblDistrict,0) != null && !(this.txtNameDistrict.getText().isEmpty())){
            int idDistrict = Integer.parseInt((String) checkTableSelection(tblDistrict, 0));
            this.district.setIdDistrict(idDistrict);
            this.district.setNameDistrict(this.txtNameDistrict.getText());
            System.out.println(this.districtBO.updateDistrict(district));
            getDistricts();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateDistrictActionPerformed

    private void btnInsertDistrictActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertDistrictActionPerformed
        if(!this.txtNameDistrict.getText().isEmpty()){
            this.district.setNameDistrict(this.txtNameDistrict.getText());
            System.out.println(districtBO.insertDistrict(district));
            getDistricts();
        }
        else {
            JOptionPane.showMessageDialog(null, "Error District not inserted!");
        }
    }//GEN-LAST:event_btnInsertDistrictActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertDistrict;
    private javax.swing.JButton btnManageAdresses;
    private javax.swing.JButton btnUpdateDistrict;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDistricts;
    private javax.swing.JLabel lblNameDistrict;
    private javax.swing.JTable tblDistrict;
    private javax.swing.JTextField txtNameDistrict;
    // End of variables declaration//GEN-END:variables
}
