/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.EventDataPK;

import B_Layer.CountryBO;
import B_Layer.DemonymBO;
import Entities.Country;
import Entities.Demonym;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jox
 */
public class TableCountries extends javax.swing.JPanel {
    private JPanel pnlContent;
    private final CountryBO countryBO = new CountryBO();
    private final Country country = new Country();
    private final DemonymBO demonymBO = new DemonymBO();
    private TableProvinces provinces;
    
    /**
     * Creates new form TableCountries
     */
    public TableCountries(JPanel pnlContent) {
        initComponents();
        this.pnlContent = pnlContent;
        provinces = new TableProvinces(pnlContent);
        fillCboxDemonym();
        getCountries();
    }
    
    //Fill Combobox with List of Demonyms
    public void fillCboxDemonym(){
        try {
            ArrayList<Demonym> list = demonymBO.getList();
            for(int i =0; i < list.size();i++){
                this.cmbDemonymCountry.addItem(list.get(i).getNameDemonym());
            }
        } catch (SQLException ex) {
            Logger.getLogger(TablePeople.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void SetContinentToCountry(int idContinent){
        country.setIdContinent(idContinent);
    }
    
    public void getCountries(){
            this.tblCountry.setModel(countryBO.getCountrys());
            TableColumnModel tblModelColumn = this.tblCountry.getColumnModel();
            tblModelColumn.removeColumn(tblModelColumn.getColumn(0));
    }
    
    public void getIdDemonym(){
        try {
            ArrayList<Demonym> list = this.demonymBO.getList();
            int pos = this.cmbDemonymCountry.getSelectedIndex();
            this.country.setIdDemonym(list.get(pos).getIdDemonym());
            
            System.out.println(this.cmbDemonymCountry.getSelectedItem());
        } catch (SQLException ex) {
            Logger.getLogger(TableCountries.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private Object checkTableSelection(JTable table, int column){
        Object user = null;
        if(!table.getSelectionModel().isSelectionEmpty())
        {
            int row = table.getSelectedRow();
            user = table.getModel().getValueAt(row, column);
            //return user;
        }
        return user;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCountries = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCountry = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnUpdateCountry = new javax.swing.JButton();
        lblNameCountry = new javax.swing.JLabel();
        txtNameCountry = new javax.swing.JTextField();
        lblDemonymCountry = new javax.swing.JLabel();
        cmbDemonymCountry = new javax.swing.JComboBox<>();
        btnInsertCountry = new javax.swing.JButton();
        btnManageProvinces = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        lblCountries.setBackground(new java.awt.Color(94, 4, 32));
        lblCountries.setMaximumSize(new java.awt.Dimension(834, 578));
        lblCountries.setMinimumSize(new java.awt.Dimension(834, 578));

        tblCountry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblCountry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCountryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCountry);

        jPanel2.setBackground(new java.awt.Color(152, 12, 51));

        btnUpdateCountry.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUpdateCountry.setText("UPDATE");
        btnUpdateCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCountryActionPerformed(evt);
            }
        });

        lblNameCountry.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblNameCountry.setForeground(new java.awt.Color(255, 255, 255));
        lblNameCountry.setText("Name");

        lblDemonymCountry.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblDemonymCountry.setForeground(new java.awt.Color(255, 255, 255));
        lblDemonymCountry.setText("Demonym");

        cmbDemonymCountry.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbDemonymCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDemonymCountryActionPerformed(evt);
            }
        });

        btnInsertCountry.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnInsertCountry.setText("INSERT");
        btnInsertCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertCountryActionPerformed(evt);
            }
        });

        btnManageProvinces.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnManageProvinces.setText("Manage Province");
        btnManageProvinces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProvincesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDemonymCountry)
                            .addComponent(lblNameCountry))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDemonymCountry, 0, 230, Short.MAX_VALUE)
                            .addComponent(txtNameCountry))
                        .addGap(221, 221, 221)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUpdateCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageProvinces))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInsertCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnInsertCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateCountry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNameCountry)
                        .addComponent(txtNameCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDemonymCountry)
                    .addComponent(cmbDemonymCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageProvinces, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Countries");

        javax.swing.GroupLayout lblCountriesLayout = new javax.swing.GroupLayout(lblCountries);
        lblCountries.setLayout(lblCountriesLayout);
        lblCountriesLayout.setHorizontalGroup(
            lblCountriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblCountriesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(lblCountriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        lblCountriesLayout.setVerticalGroup(
            lblCountriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblCountriesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblCountries, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 543, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(lblCountries, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblCountryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCountryMouseClicked
        int selection = this.tblCountry.rowAtPoint(evt.getPoint());
        String type = this.tblCountry.getValueAt(selection, 0)+"";
        
        this.txtNameCountry.setText(this.tblCountry.getValueAt(selection, 1)+"");
    }//GEN-LAST:event_tblCountryMouseClicked

    private void btnUpdateCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCountryActionPerformed
        if (this.checkTableSelection(tblCountry,0) != null && !(this.txtNameCountry.getText().isEmpty())){
            int idCountry = Integer.parseInt((String) checkTableSelection(tblCountry, 0));
            this.country.setIdCountry(idCountry);
            this.country.setNameCountry(this.txtNameCountry.getText());
            getIdDemonym();
            
            System.out.println(this.countryBO.updateCountry(country));
            getCountries();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnUpdateCountryActionPerformed

    private void btnInsertCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertCountryActionPerformed
        if(!this.txtNameCountry.getText().isEmpty()){
            this.country.setNameCountry(this.txtNameCountry.getText());
            getIdDemonym();
            System.out.println(countryBO.insertCountry(country));
            getCountries();
        }
        else {
            JOptionPane.showMessageDialog(null, "Error Country not inserted!");
        }
    }//GEN-LAST:event_btnInsertCountryActionPerformed

    private void cmbDemonymCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDemonymCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDemonymCountryActionPerformed

    private void btnManageProvincesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProvincesActionPerformed
        if(this.checkTableSelection(tblCountry, WIDTH) != null ){
            int idCountry = Integer.parseInt((String) checkTableSelection(tblCountry, 0));
            this.provinces.SetContryToProvince(idCountry);
            this.provinces.setSize(834, 567);
            this.provinces.setLocation(0,0);
            pnlContent.removeAll();
            pnlContent.add(this.provinces,BorderLayout.CENTER);
            pnlContent.revalidate();
            pnlContent.repaint();
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Country");
        }
    }//GEN-LAST:event_btnManageProvincesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertCountry;
    private javax.swing.JButton btnManageProvinces;
    private javax.swing.JButton btnUpdateCountry;
    private javax.swing.JComboBox<String> cmbDemonymCountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lblCountries;
    private javax.swing.JLabel lblDemonymCountry;
    private javax.swing.JLabel lblNameCountry;
    private javax.swing.JTable tblCountry;
    private javax.swing.JTextField txtNameCountry;
    // End of variables declaration//GEN-END:variables
}
