/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.CatalogsPK;

import B_Layer.ParameterBO;
import Entities.ParameterEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jox
 */
public class TableParameters extends javax.swing.JPanel {
    private final ParameterBO parameterBO = new ParameterBO();
    private final ParameterEvent parameter = new ParameterEvent();
    /**
     * Creates new form TableParameters
     */
    public TableParameters() {
        initComponents();
        this.getParameters();
    }
    
    public void getParameters(){
            tblParameter.setModel(parameterBO.getParameters());
            TableColumnModel tblModelColumn = tblParameter.getColumnModel();
            tblModelColumn.removeColumn(tblModelColumn.getColumn(0));
    }
    
    private Object checkTableSelection(JTable table, int column){
        Object parameter = null;
        if(!table.getSelectionModel().isSelectionEmpty())
        {
            int row = table.getSelectedRow();
            parameter = table.getModel().getValueAt(row, column);
            //return parameter;
        }
        return parameter;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblParameter = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnDeleteParameter = new javax.swing.JButton();
        btnUpdateParameter = new javax.swing.JButton();
        lblNameParameter = new javax.swing.JLabel();
        txtNameParameter = new javax.swing.JTextField();
        btnInsertParameter = new javax.swing.JButton();
        lblValueParameter = new javax.swing.JLabel();
        cmbValueParameter = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(94, 4, 32));
        jPanel1.setMaximumSize(new java.awt.Dimension(834, 578));
        jPanel1.setMinimumSize(new java.awt.Dimension(834, 578));

        tblParameter.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblParameter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblParameterMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblParameter);

        jPanel2.setBackground(new java.awt.Color(152, 12, 51));

        btnDeleteParameter.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnDeleteParameter.setText("DELETE");
        btnDeleteParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteParameterActionPerformed(evt);
            }
        });

        btnUpdateParameter.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUpdateParameter.setText("UPDATE");
        btnUpdateParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateParameterActionPerformed(evt);
            }
        });

        lblNameParameter.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblNameParameter.setForeground(new java.awt.Color(255, 255, 255));
        lblNameParameter.setText("Name");

        btnInsertParameter.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnInsertParameter.setText("INSERT");
        btnInsertParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertParameterActionPerformed(evt);
            }
        });

        lblValueParameter.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblValueParameter.setForeground(new java.awt.Color(255, 255, 255));
        lblValueParameter.setText("Value");

        cmbValueParameter.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbValueParameter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal", "Admin" }));
        cmbValueParameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbValueParameterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNameParameter)
                            .addComponent(lblValueParameter))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNameParameter, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(cmbValueParameter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 300, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnInsertParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnInsertParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateParameter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNameParameter)
                        .addComponent(txtNameParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValueParameter)
                    .addComponent(cmbValueParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblParameterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblParameterMouseClicked
        int selection = this.tblParameter.rowAtPoint(evt.getPoint());
        String type = this.tblParameter.getValueAt(selection, 0)+"";
        if (type.toLowerCase().equals("normal"))
            this.cmbValueParameter.setSelectedIndex(0);
        else
            this.cmbValueParameter.setSelectedIndex(1);
        this.txtNameParameter.setText(this.tblParameter.getValueAt(selection, 0)+"");
    }//GEN-LAST:event_tblParameterMouseClicked

    private void btnDeleteParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteParameterActionPerformed
        if (this.checkTableSelection(tblParameter,0) != null){
            int idParameter = Integer.parseInt((String) checkTableSelection(tblParameter, 0));
            this.parameter.setIdParameter(idParameter);
            
            System.out.println(this.parameterBO.deleteParameter(idParameter));
            this.getParameters();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteParameterActionPerformed

    private void btnUpdateParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateParameterActionPerformed
        if (this.checkTableSelection(tblParameter,0) != null && !(this.txtNameParameter.getText().isEmpty() )){
            int idParameter = Integer.parseInt((String)checkTableSelection(tblParameter, 0));
            this.parameter.setIdParameter(idParameter);
            
            String type = this.cmbValueParameter.getSelectedItem().toString().toLowerCase();
            if (type.toLowerCase().equals("normal"))
                this.parameter.setValueParameter(1);
            else
                this.parameter.setValueParameter(2);
            this.parameter.setNameParameter(this.txtNameParameter.getText());
            
            System.out.println(this.parameterBO.updateParameter(parameter));
            this.getParameters();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateParameterActionPerformed

    private void btnInsertParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertParameterActionPerformed
        if (!(this.txtNameParameter.getText().isEmpty())){
            
            if (this.cmbValueParameter.getSelectedItem().toString().toLowerCase().equals("normal"))
                this.parameter.setValueParameter(1);
            else
                this.parameter.setValueParameter(2);

            this.parameter.setNameParameter(this.txtNameParameter.getText());
            System.out.println(parameterBO.insertParameter(parameter));
            this.getParameters();
        }
        else {
            JOptionPane.showMessageDialog(null, "Invalid name, null value encountered");
        }
    }//GEN-LAST:event_btnInsertParameterActionPerformed

    private void cmbValueParameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbValueParameterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbValueParameterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteParameter;
    private javax.swing.JButton btnInsertParameter;
    private javax.swing.JButton btnUpdateParameter;
    private javax.swing.JComboBox<String> cmbValueParameter;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNameParameter;
    private javax.swing.JLabel lblValueParameter;
    private javax.swing.JTable tblParameter;
    private javax.swing.JTextField txtNameParameter;
    // End of variables declaration//GEN-END:variables
}
