/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.CatalogsPK;

import B_Layer.HelperTypeBO;
import Entities.HelperType;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jox
 */
public class TableHelperType extends javax.swing.JPanel {
    private final HelperTypeBO HelperBO = new HelperTypeBO();
    private final HelperType Helper = new HelperType();
    /**
     * Creates new form TableHelperType
     */
    public TableHelperType() {
        initComponents();
        getHelperType();
    }
     
    public void getHelperType(){
            tblHelperType.setModel(HelperBO.getHelperType());
            TableColumnModel tblModelColumn = tblHelperType.getColumnModel();
            tblModelColumn.removeColumn(tblModelColumn.getColumn(0));
    }    

    private Object checkTableSelection(JTable table, int column){
        Object user = null;
        if(!table.getSelectionModel().isSelectionEmpty())
        {
            int row = table.getSelectedRow();
            user = table.getModel().getValueAt(row, column);
            //return user;
        }
        return user;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHelperType = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnDeleteHelperType = new javax.swing.JButton();
        btnUpdateHelperType = new javax.swing.JButton();
        lblNameHelperType = new javax.swing.JLabel();
        txtNameHelperType = new javax.swing.JTextField();
        btnInsertHelperType = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(94, 4, 32));
        jPanel1.setMaximumSize(new java.awt.Dimension(834, 578));
        jPanel1.setMinimumSize(new java.awt.Dimension(834, 578));

        tblHelperType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblHelperType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHelperTypeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHelperType);

        jPanel2.setBackground(new java.awt.Color(152, 12, 51));

        btnDeleteHelperType.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnDeleteHelperType.setText("DELETE");
        btnDeleteHelperType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteHelperTypeActionPerformed(evt);
            }
        });

        btnUpdateHelperType.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUpdateHelperType.setText("UPDATE");
        btnUpdateHelperType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateHelperTypeActionPerformed(evt);
            }
        });

        lblNameHelperType.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblNameHelperType.setForeground(new java.awt.Color(255, 255, 255));
        lblNameHelperType.setText("Name");

        btnInsertHelperType.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnInsertHelperType.setText("INSERT");
        btnInsertHelperType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertHelperTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNameHelperType)
                        .addGap(59, 59, 59)
                        .addComponent(txtNameHelperType, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateHelperType, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteHelperType, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnInsertHelperType, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnInsertHelperType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateHelperType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameHelperType, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNameHelperType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnDeleteHelperType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblHelperTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHelperTypeMouseClicked

    }//GEN-LAST:event_tblHelperTypeMouseClicked

    private void btnDeleteHelperTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteHelperTypeActionPerformed
        if(this.checkTableSelection(tblHelperType,0) != null){
            int idHelperType= Integer.parseInt((String) checkTableSelection(tblHelperType, 0));
            System.out.println(HelperBO.deleteHelperType(idHelperType));
            this.getHelperType();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteHelperTypeActionPerformed

    private void btnUpdateHelperTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateHelperTypeActionPerformed
        if(this.checkTableSelection(tblHelperType,0) != null &&
                !(this.txtNameHelperType.getText().isEmpty())){
            int idHelperType= Integer.parseInt((String) checkTableSelection(tblHelperType, 0));
            this.Helper.setIdHelperType(idHelperType);
            this.Helper.setNameHelperType(this.txtNameHelperType.getText());
            System.out.println(HelperBO.updateHelperType(Helper));
            this.getHelperType();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateHelperTypeActionPerformed

    private void btnInsertHelperTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertHelperTypeActionPerformed
        if (this.checkTableSelection(tblHelperType,0) != null){
            int idUser = Integer.parseInt((String) checkTableSelection(tblHelperType, 0));
            this.Helper.setNameHelperType(this.txtNameHelperType.getText());
            System.out.println(HelperBO.getHelperType());
            this.getHelperType();
        }
        else {
            JOptionPane.showMessageDialog(null, "Invalid name, null value encountered");
        }
    }//GEN-LAST:event_btnInsertHelperTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteHelperType;
    private javax.swing.JButton btnInsertHelperType;
    private javax.swing.JButton btnUpdateHelperType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNameHelperType;
    private javax.swing.JTable tblHelperType;
    private javax.swing.JTextField txtNameHelperType;
    // End of variables declaration//GEN-END:variables
}
