/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.CatalogsPK;

import B_Layer.WorkerTypeBO;
import Entities.WorkerType;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author jox
 */
public class TableWorkerTypes extends javax.swing.JPanel {
    private final WorkerTypeBO workerBO = new WorkerTypeBO();
    private final WorkerType worker = new WorkerType();
    
    /**
     * Creates new form WorkerType
     */
    public TableWorkerTypes() {
        initComponents();
        getWorkerTypes();
    }

    public void getWorkerTypes(){
        tblWorkerType.setModel(workerBO.getWorkerType());
        TableColumnModel tblModelColumn = tblWorkerType.getColumnModel();
        tblModelColumn.removeColumn(tblModelColumn.getColumn(0));
    }
    
    private Object checkTableSelection(JTable table, int column){
        Object user = null;
        if(!table.getSelectionModel().isSelectionEmpty())
        {
            int row = table.getSelectedRow();
            user = table.getModel().getValueAt(row, column);
            //return user;
        }
        return user;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkerType = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnDeleteWorkerType = new javax.swing.JButton();
        btnUpdateWorkerType = new javax.swing.JButton();
        lblNameWorkerType = new javax.swing.JLabel();
        txtNameWorkerType = new javax.swing.JTextField();
        btnInsertWorkerType = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(94, 4, 32));
        jPanel1.setMaximumSize(new java.awt.Dimension(834, 578));
        jPanel1.setMinimumSize(new java.awt.Dimension(834, 578));

        tblWorkerType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblWorkerType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblWorkerTypeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblWorkerType);

        jPanel2.setBackground(new java.awt.Color(152, 12, 51));

        btnDeleteWorkerType.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnDeleteWorkerType.setText("DELETE");
        btnDeleteWorkerType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteWorkerTypeActionPerformed(evt);
            }
        });

        btnUpdateWorkerType.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnUpdateWorkerType.setText("UPDATE");
        btnUpdateWorkerType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateWorkerTypeActionPerformed(evt);
            }
        });

        lblNameWorkerType.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblNameWorkerType.setForeground(new java.awt.Color(255, 255, 255));
        lblNameWorkerType.setText("Name");

        btnInsertWorkerType.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        btnInsertWorkerType.setText("INSERT");
        btnInsertWorkerType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertWorkerTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNameWorkerType)
                        .addGap(59, 59, 59)
                        .addComponent(txtNameWorkerType, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(296, 296, 296)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdateWorkerType, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteWorkerType, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnInsertWorkerType, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnInsertWorkerType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUpdateWorkerType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameWorkerType, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNameWorkerType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnDeleteWorkerType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblWorkerTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblWorkerTypeMouseClicked

    }//GEN-LAST:event_tblWorkerTypeMouseClicked

    private void btnDeleteWorkerTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteWorkerTypeActionPerformed
        if (this.checkTableSelection(tblWorkerType,0) != null){
            int idWorkerType = Integer.parseInt((String) checkTableSelection(tblWorkerType, 0));
            this.worker.setIdWorkerType(idWorkerType);
            System.out.println(this.workerBO.deleteWorkerType(idWorkerType));
            this.getWorkerTypes();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteWorkerTypeActionPerformed

    private void btnUpdateWorkerTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateWorkerTypeActionPerformed
        if (this.checkTableSelection(tblWorkerType,0) != null &&
           !(this.txtNameWorkerType.getText().isEmpty())){
            int idWorkerType = Integer.parseInt((String) checkTableSelection(tblWorkerType, 0));
            this.worker.setIdWorkerType(idWorkerType);
            this.worker.setNameWorkerType(this.txtNameWorkerType.getText());
            System.out.println(this.workerBO.updateWorkerType(worker));
            this.getWorkerTypes();
        }
        else {
            JOptionPane.showMessageDialog(null, "Register not Selected", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateWorkerTypeActionPerformed

    private void btnInsertWorkerTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertWorkerTypeActionPerformed
        if(!(this.txtNameWorkerType.getText().isEmpty())){
            this.worker.setNameWorkerType(this.txtNameWorkerType.getText());
            System.out.println(workerBO.insertWorkerType(worker));
            this.getWorkerTypes();
        }
        else {
            JOptionPane.showMessageDialog(null, "Invalid name, null value encountered");
        }
    }//GEN-LAST:event_btnInsertWorkerTypeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteWorkerType;
    private javax.swing.JButton btnInsertWorkerType;
    private javax.swing.JButton btnUpdateWorkerType;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNameWorkerType;
    private javax.swing.JTable tblWorkerType;
    private javax.swing.JTextField txtNameWorkerType;
    // End of variables declaration//GEN-END:variables
}
